import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "AI Supplementary Terms — MindPath BI",
  description: "Terms governing the use of AI-powered features within the MindPath BI platform.",
};

export default function AITermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <nav className="border-b border-border">
        <div className="mx-auto flex h-12 max-w-3xl items-center px-6">
          <Link href="/" className="flex items-center gap-2">
            <div className="flex h-7 w-7 items-center justify-center rounded-md bg-foreground">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className="text-background">
                <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z" />
                <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z" />
              </svg>
            </div>
            <span className="text-sm font-semibold tracking-tight">MindPath BI</span>
          </Link>
        </div>
      </nav>

      <main className="mx-auto max-w-3xl px-6 py-16">
        <h1 className="text-4xl font-bold tracking-tight">AI Supplementary Terms</h1>
        <p className="mt-2 text-sm text-muted">Last updated: April 2026</p>

        <div className="mt-10 space-y-8 text-[15px] leading-relaxed text-muted">
          <p>
            These AI Supplementary Terms (&ldquo;AI Terms&rdquo;) govern your use of AI-powered features
            within the MindPath BI platform (&ldquo;AI Features&rdquo;). These AI Terms supplement and form
            part of the{" "}
            <Link href="/terms" className="text-foreground underline underline-offset-2 hover:opacity-80">Terms of Service</Link>.
            Where there is a conflict between these AI Terms and the Terms of Service regarding AI Features,
            these AI Terms prevail.
          </p>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-foreground">1. Scope</h2>
            <p>These AI Terms apply to all AI-powered features of the Service, including but not limited to:</p>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>AI Copilot (chat-based assistance, context-aware suggestions)</li>
              <li>Suggested replies and draft generation</li>
              <li>Thread and conversation summaries</li>
              <li>Message classification (category, urgency, sentiment)</li>
              <li>Contact insights and AI-generated profiles</li>
              <li>Knowledge Base ranking and retrieval</li>
              <li>Routing recommendations</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-foreground">2. Definitions</h2>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li><strong className="text-foreground">&ldquo;AI Features&rdquo;</strong> means any feature of the Service that uses artificial intelligence or machine learning models to process data and generate outputs.</li>
              <li><strong className="text-foreground">&ldquo;Input&rdquo;</strong> means any data, content, or instructions submitted to AI Features by you or your authorized users.</li>
              <li><strong className="text-foreground">&ldquo;Output&rdquo;</strong> means any content, suggestions, classifications, or other results generated by AI Features in response to Input.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-foreground">3. Intellectual Property</h2>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li><strong className="text-foreground">Input:</strong> You retain all ownership rights in your Input. Submitting Input to AI Features does not transfer any intellectual property rights to us.</li>
              <li><strong className="text-foreground">Output:</strong> Output is provided as assistive content for your use. Due to the nature of AI, Output may not be unique — other users may receive similar or identical Output from similar Input. You are responsible for reviewing and adapting Output before any use.</li>
              <li>We do not claim ownership of Output generated from your Input.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-foreground">4. No Model Training</h2>
            <p>We make the following commitments regarding your data and AI models:</p>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>Your Customer Content (including Input and Output) is <strong className="text-foreground">not used to train, fine-tune, or improve</strong> any general-purpose AI or machine learning model.</li>
              <li>Our AI provider (Google Gemini) is <strong className="text-foreground">contractually restricted</strong> from using your data for training or improving their models for general use.</li>
              <li>We may use aggregated, anonymized, non-identifiable metadata (such as feature usage patterns) to improve the Service, but never individual customer content.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-foreground">5. AI Provider</h2>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>The primary AI provider for the Service is <strong className="text-foreground">Google Gemini</strong>, as disclosed on our{" "}
                <Link href="/subprocessors" className="text-foreground underline underline-offset-2 hover:opacity-80">Subprocessors</Link> page.</li>
              <li>AI processing may occur in the United States or European Union depending on provider infrastructure. Transfer mechanisms are described in our{" "}
                <Link href="/dpa" className="text-foreground underline underline-offset-2 hover:opacity-80">Data Processing Addendum</Link>.</li>
              <li>Third-party AI provider downtime is excluded from the{" "}
                <Link href="/sla" className="text-foreground underline underline-offset-2 hover:opacity-80">Service Level Agreement</Link> uptime calculation.</li>
              <li>We may change or add AI providers. Material changes are reflected on the Subprocessors page with advance notice per our{" "}
                <Link href="/dpa" className="text-foreground underline underline-offset-2 hover:opacity-80">DPA</Link> Sub-processor notification process.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-foreground">6. Accuracy and Limitations</h2>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>AI Features are provided <strong className="text-foreground">&ldquo;as is&rdquo;</strong> without warranty of accuracy, completeness, or fitness for a particular purpose.</li>
              <li>Output may be inaccurate, incomplete, biased, or may not reflect events occurring after the AI model&rsquo;s training cutoff date.</li>
              <li>You must <strong className="text-foreground">independently verify</strong> any factual claims, business data, or legal interpretations present in Output before relying on or acting upon them.</li>
              <li>We do not guarantee that AI Features will be available at all times or that Output quality will be consistent.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-foreground">7. Human Oversight</h2>
            <p>You agree to maintain appropriate human oversight of AI Features:</p>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>All AI-generated <strong className="text-foreground">customer-facing content</strong> (replies, messages, communications) should be reviewed by a human before sending.</li>
              <li>AI classifications (urgency, sentiment, category) and routing suggestions are assistive and should not be the sole basis for consequential decisions without human review.</li>
              <li>Your organization is responsible for establishing and enforcing internal policies regarding AI output review.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-foreground">8. AI Transparency</h2>
            <p>In accordance with the EU AI Act (Article 52) and our commitment to transparency:</p>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>AI-powered chat interfaces clearly disclose their AI-powered nature through interface chrome, empty states, or first-turn notifications.</li>
              <li>Non-chat AI-generated content (summaries, classifications, insights) is labeled as &ldquo;AI-generated&rdquo; or equivalent at point of display.</li>
              <li>We review and update our AI transparency practices at least annually or when material changes to AI features occur.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-foreground">9. Prohibited Uses</h2>
            <p>You agree not to use AI Features to:</p>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li><strong className="text-foreground">Automated decision-making with legal effect</strong> — In the EEA, UK, and Switzerland, you must not use AI Features as the sole basis for decisions that produce legal effects or similarly significantly affect individuals, including but not limited to: credit/lending decisions, insurance underwriting, hiring or recruitment screening, personalized pricing or marketing offers, medical diagnosis or treatment, government benefit determinations.</li>
              <li><strong className="text-foreground">Misrepresentation</strong> — You must not present AI-generated Output as solely human-generated in contexts where the distinction is material.</li>
              <li><strong className="text-foreground">Competing models</strong> — You must not use Output to develop, train, or improve AI models that compete with MindPath BI or its AI providers.</li>
              <li><strong className="text-foreground">Spam and manipulation</strong> — You must not use AI Features to generate spam, phishing content, disinformation, or electoral campaign material.</li>
              <li><strong className="text-foreground">Circumvention</strong> — You must not attempt to circumvent usage limits, safety filters, or content policies applied to AI Features.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-foreground">10. Usage Limits</h2>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>AI Features are subject to usage limits based on your subscription plan.</li>
              <li>We may limit, throttle, or temporarily suspend AI Feature access to prevent abuse, maintain quality of service, or comply with AI provider rate limits.</li>
              <li>We will provide reasonable notice of material changes to usage limits where practicable.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-foreground">11. Contact</h2>
            <p>
              For questions about these AI Terms, contact us at{" "}
              <a href="mailto:josef@mindpathbi.com" className="text-foreground underline underline-offset-2 hover:opacity-80">josef@mindpathbi.com</a>.
            </p>
          </section>
        </div>

        <div className="mt-16 border-t border-border pt-8 text-center text-xs text-muted">
          &copy; 2026 MindPath BI. All rights reserved.
        </div>
      </main>
    </div>
  );
}
