import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, LegalSection } from "@/components/legal/legal-page";

export const metadata: Metadata = {
  title: "AI Supplementary Terms — MindPath BI",
  description:
    "Terms governing the use of AI-powered features within the MindPath BI platform.",
};

export default function AITermsPage() {
  return (
    <LegalPage
      fieldReport="AI-01"
      docSlug="AI-TERMS"
      title="AI supplementary terms."
      subtitle="How the AI layer of the platform is governed — training, transparency, human oversight, and prohibited uses."
      version="1.0"
      lastUpdated="April 2026"
    >
      <p>
        These AI Supplementary Terms (&ldquo;AI Terms&rdquo;) govern your use of
        AI-powered features within the MindPath BI platform (&ldquo;AI
        Features&rdquo;). They supplement and form part of the{" "}
        <Link href="/terms">Terms of Service</Link>. Where there is a conflict
        between these AI Terms and the Terms of Service regarding AI Features,
        these AI Terms prevail.
      </p>

      <LegalSection num="01" tag="[SCOPE]" title="Scope">
        <p>
          These AI Terms apply to all AI-powered features of the Service,
          including but not limited to:
        </p>
        <ul>
          <li>AI Copilot (chat-based assistance, context-aware suggestions)</li>
          <li>Suggested replies and draft generation</li>
          <li>Thread and conversation summaries</li>
          <li>Message classification (category, urgency, sentiment)</li>
          <li>Contact insights and AI-generated profiles</li>
          <li>Knowledge Base ranking and retrieval</li>
          <li>Routing recommendations</li>
        </ul>
      </LegalSection>

      <LegalSection num="02" tag="[DEFINITIONS]" title="Definitions">
        <ul>
          <li>
            <strong>&ldquo;AI Features&rdquo;</strong> means any feature of the
            Service that uses artificial intelligence or machine learning models
            to process data and generate outputs.
          </li>
          <li>
            <strong>&ldquo;Input&rdquo;</strong> means any data, content, or
            instructions submitted to AI Features by you or your authorized
            users.
          </li>
          <li>
            <strong>&ldquo;Output&rdquo;</strong> means any content, suggestions,
            classifications, or other results generated by AI Features in
            response to Input.
          </li>
        </ul>
      </LegalSection>

      <LegalSection num="03" tag="[IP]" title="Intellectual property">
        <ul>
          <li>
            <strong>Input:</strong> you retain all ownership rights in your
            Input. Submitting Input to AI Features does not transfer any
            intellectual property rights to us.
          </li>
          <li>
            <strong>Output:</strong> Output is provided as assistive content for
            your use. Due to the nature of AI, Output may not be unique — other
            users may receive similar or identical Output from similar Input.
            You are responsible for reviewing and adapting Output before any
            use.
          </li>
          <li>We do not claim ownership of Output generated from your Input.</li>
        </ul>
      </LegalSection>

      <LegalSection num="04" tag="[NO-TRAIN]" title="No model training">
        <p>
          We make the following commitments regarding your data and AI models:
        </p>
        <ul>
          <li>
            Your Customer Content (including Input and Output) is{" "}
            <strong>not used to train, fine-tune, or improve</strong> any
            general-purpose AI or machine learning model.
          </li>
          <li>
            Our AI providers are{" "}
            <strong>contractually restricted</strong> from using your data to
            train or improve their models for general use.
          </li>
          <li>
            We may use aggregated, anonymized, non-identifiable metadata (such
            as feature usage patterns) to improve the Service, but never
            individual customer content.
          </li>
        </ul>
      </LegalSection>

      <LegalSection num="05" tag="[PROVIDER]" title="AI provider">
        <ul>
          <li>
            The identity and location of AI providers in use are disclosed by
            category on our <Link href="/subprocessors">Subprocessors</Link>{" "}
            page; specific providers are confirmed under contract.
          </li>
          <li>
            AI processing may occur in the United States or European Union
            depending on provider infrastructure. Transfer mechanisms are
            described in our <Link href="/dpa">Data Processing Addendum</Link>.
          </li>
          <li>
            Third-party AI provider downtime is excluded from the{" "}
            <Link href="/sla">Service Level Agreement</Link> uptime calculation.
          </li>
          <li>
            We may change or add AI providers. Material changes are reflected on
            the Subprocessors page with advance notice per our{" "}
            <Link href="/dpa">DPA</Link> sub-processor notification process.
          </li>
        </ul>
      </LegalSection>

      <LegalSection num="06" tag="[ACCURACY]" title="Accuracy and limitations">
        <ul>
          <li>
            AI Features are provided <strong>&ldquo;as is&rdquo;</strong>{" "}
            without warranty of accuracy, completeness, or fitness for a
            particular purpose.
          </li>
          <li>
            Output may be inaccurate, incomplete, biased, or may not reflect
            events occurring after the AI model&rsquo;s training cutoff date.
          </li>
          <li>
            You must <strong>independently verify</strong> any factual claims,
            business data, or legal interpretations present in Output before
            relying on or acting upon them.
          </li>
          <li>
            We do not guarantee that AI Features will be available at all times
            or that Output quality will be consistent.
          </li>
        </ul>
      </LegalSection>

      <LegalSection num="07" tag="[OVERSIGHT]" title="Human oversight">
        <p>You agree to maintain appropriate human oversight of AI Features:</p>
        <ul>
          <li>
            All AI-generated <strong>customer-facing content</strong> (replies,
            messages, communications) should be reviewed by a human before
            sending.
          </li>
          <li>
            AI classifications (urgency, sentiment, category) and routing
            suggestions are assistive and should not be the sole basis for
            consequential decisions without human review.
          </li>
          <li>
            Your organization is responsible for establishing and enforcing
            internal policies regarding AI output review.
          </li>
        </ul>
      </LegalSection>

      <LegalSection num="08" tag="[TRANSPARENCY]" title="AI transparency">
        <p>
          In accordance with the EU AI Act (Article 52) and our commitment to
          transparency:
        </p>
        <ul>
          <li>
            AI-powered chat interfaces clearly disclose their AI-powered nature
            through interface chrome, empty states, or first-turn notifications.
          </li>
          <li>
            Non-chat AI-generated content (summaries, classifications, insights)
            is labeled as &ldquo;AI-generated&rdquo; or equivalent at point of
            display.
          </li>
          <li>
            We review and update our AI transparency practices at least annually
            or when material changes to AI features occur.
          </li>
        </ul>
      </LegalSection>

      <LegalSection num="09" tag="[PROHIBITED]" title="Prohibited uses">
        <p>You agree not to use AI Features to:</p>
        <ul>
          <li>
            <strong>Automated decision-making with legal effect</strong> — in
            the EEA, UK, and Switzerland, you must not use AI Features as the
            sole basis for decisions that produce legal effects or similarly
            significantly affect individuals, including but not limited to:
            credit/lending decisions, insurance underwriting, hiring or
            recruitment screening, personalized pricing or marketing offers,
            medical diagnosis or treatment, government benefit determinations.
          </li>
          <li>
            <strong>Misrepresentation</strong> — you must not present
            AI-generated Output as solely human-generated in contexts where the
            distinction is material.
          </li>
          <li>
            <strong>Competing models</strong> — you must not use Output to
            develop, train, or improve AI models that compete with MindPath BI
            or its AI providers.
          </li>
          <li>
            <strong>Spam and manipulation</strong> — you must not use AI
            Features to generate spam, phishing content, disinformation, or
            electoral campaign material.
          </li>
          <li>
            <strong>Circumvention</strong> — you must not attempt to circumvent
            usage limits, safety filters, or content policies applied to AI
            Features.
          </li>
        </ul>
      </LegalSection>

      <LegalSection num="10" tag="[LIMITS]" title="Usage limits">
        <ul>
          <li>
            AI Features are subject to usage limits based on your subscription
            plan.
          </li>
          <li>
            We may limit, throttle, or temporarily suspend AI Feature access to
            prevent abuse, maintain quality of service, or comply with AI
            provider rate limits.
          </li>
          <li>
            We will provide reasonable notice of material changes to usage
            limits where practicable.
          </li>
        </ul>
      </LegalSection>

      <LegalSection num="11" tag="[CONTACT]" title="Contact">
        <p>
          For questions about these AI Terms, contact{" "}
          <a href="mailto:josef@mindpathbi.com">josef@mindpathbi.com</a>.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
